# Generated by Django 2.1.2 on 2018-10-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20181018_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
