# Generated by Django 2.1.2 on 2018-10-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auction.Profile'),
            preserve_default=False,
        ),
    ]
