# Generated by Django 2.1.2 on 2018-10-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auction_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
