# Generated by Django 2.1.2 on 2018-10-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='slug',
            field=models.SlugField(default='a', unique=True),
            preserve_default=False,
        ),
    ]
