# Generated by Django 2.1.2 on 2018-10-19 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auto_20181019_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
