# Generated by Django 2.1.2 on 2018-10-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auction_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[(1, 'Open'), (2, 'Resolve'), (3, 'Ban'), (4, 'Expire')], default=1, max_length=2),
        ),
    ]
