# Generated by Django 2.1.2 on 2018-10-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_auction_is_actice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='is_actice',
            new_name='is_active',
        ),
    ]
