# Generated by Django 2.1.2 on 2018-10-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auto_20181019_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Resolve'), (3, 'Ban'), (4, 'Expire')], default=1),
        ),
    ]
