# Generated by Django 2.1.2 on 2018-10-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_auto_20181019_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='about',
            new_name='description',
        ),
    ]
