# Generated by Django 2.1.2 on 2018-10-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_auto_20181019_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-price']},
        ),
    ]
