# Generated by Django 2.1.2 on 2018-10-23 19:57

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0020_auction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0.0'), default_currency='IDR', max_digits=14, verbose_name='Minimum Price'),
        ),
    ]
