# Generated by Django 2.1.2 on 2018-10-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0022_auto_20181024_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
