# Generated by Django 2.1.2 on 2018-10-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0025_auto_20181025_0546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-bid_price']},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='bid_price',
        ),
    ]
